### ISSUE TITLE
Issues with cert-manager

### ISSUE THREAD

**Issue by devantler** [container-registry/helm-charts-oci-proxy#17]
Hey,

I am scratching my head because the service works well for all our services but not for cert-manager. With cert-manager, it seems Chartproxy is unable to convert the Helm Chart to OCI.

These are the logs I am getting:

```yaml
proxy-2024/06/10 12:53:53 download index: https://charts.jetstack.io/index.yaml                                                                
proxy-2024/06/10 12:53:53 downloading : https://charts.jetstack.io/index.yaml                                                                   
proxy-2024/06/10 12:53:54 searching index for cert-manager with reference v1.15.0                                                                     
proxy-2024/06/10 12:53:54 downloading : https://charts.jetstack.io/charts/cert-manager-v1.15.0.tgz-pod-autoscaler@9.8.2
proxy-2024/06/10 12:53:54 searching index for cert-manager with reference v1.15.0
proxy-2024/06/10 12:53:54 downloading : https://charts.jetstack.io/charts/cert-manager-v1.15.0.tgz
proxy-2024/06/10 12:53:54 HEAD /v2/charts.jetstack.io/cert-manager/manifests/v1.15.0 404 NOT FOUND Chart prepare error
```yaml

Below is my HelmRepository and HelmRelease manifests for cert-manager:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
spec:
  insecure: true
  type: oci
  url: oci://${helm_charts_proxy_url:=chartproxy.container-registry.com}/charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1m
  chart:
    spec:
      chart: cert-manager
      version: v1.15.0
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  # https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
  values:
    # This configures cert-manager to install and upgrade CRDs as part of the Helm release.
    # https://cert-manager.io/docs/installation/helm/#helm-installation
    installCRDs: true
```

And lastly here is my HelmRelease manifest for helm-charts-oci-proxy:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-charts-oci-proxy
spec:
  interval: 1m
  chart:
    spec:
      chart: helm-charts-oci-proxy
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: helm-charts-oci-proxy
  # https://github.com/container-registry/helm-charts-oci-proxy/blob/main/chart/values.yaml
  values:
    image:
      tag: staging-202404291447
    app:
      env_vars:
        DEBUG: true
        # USE_TLS: true
        # INDEX_CACHE_TTL: 60 # for how long we have stores manifest and its related blobs
        # MANIFEST_CACHE_TTL: 14400 # for how long we store chart index file content
```

I am using a self-hosted chartproxy, as I owerwrite the `${helm_charts_proxy_url:=chartproxy.container-registry.com}` with the following url: `oci://helm-charts-oci-proxy.helm-charts-oci-proxy:9000`, so I am pretty sure that this is not related to caching. I have also checked that the the `https://charts.jetstack.io/index.yaml` looks as expected. Has anyone experienced this?
