### ISSUE TITLE
Remove default annotations from ingress on chart

### ISSUE THREAD

**Issue by EStork09** [container-registry/helm-charts-oci-proxy#22]
https://github.com/container-registry/helm-charts-oci-proxy/blob/main/chart/values.yaml#L47-L50
```
annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
```
I am using an issuer to create certs and this impacts cert-manager that it cannot have both the cluster-issuer and issuer and cannot remove it as I am running as a sub chart. Could we remove this?
