### ISSUE TITLE
Stable version of docker image

### ISSUE THREAD

**Issue by verdel** [container-registry/helm-charts-oci-proxy#9]
Do you have stable or tagged versions of Docker images in your Docker registry that correspond to the GitHub repository tags? Unfortunately, I cannot download the docker image with the tag 0.1.7.

```shell
docker pull 8gears.container-registry.com/library/helm-charts-oci-proxy:0.1.7
```
and
```shell
docker pull 8gears.container-registry.com/library/ocip:0.1.7
```
returns 
```
Error response from daemon: unknown: artifact library/ocip:0.1.7 not found
Error response from daemon: unknown: artifact library/helm-charts-oci-proxy:0.1.7 not found
```

**Comment by Vad1mo** [comment]
We migrated all helm charts to OCI charts. I'll update the references.

Thanks

**Comment by verdel** [comment]
Perhaps I didn't describe the problem in enough detail. I meant the availability of Docker images tagged in a way that corresponds to the tags in this GitHub repository, for example `0.1.7`. Currently, the chart's `values.yaml` specifies the tag `latest`, and in `Chart.yaml` `appVersion` - `a3a35bc`. I would like to have Docker images with fixed tags.

Did you mean that you will update the tag value in the Helm chart when you prepare it for publication in the OCI repository?

**Comment by gberche-orange** [comment]
@Vad1mo I'm experiencing the same issue: when trying to use tag="1.2.2" in values.yaml in the following fragment

https://github.com/container-registry/helm-charts-oci-proxy/blob/f9bc9d4afbe6bee4888cf99595c5b1bf805a079f/chart/values.yaml#L7-L11

I see failure to load the OCI image for running Deployment container with version 1.2.2                                                   

```yaml
  containerStatuses:                                                                                                                                                                   
  - image: 8gears.container-registry.com/library/helm-charts-oci-proxy:1.2.2                                                                                                           
    imageID: ""                                                                                                                                                                        
    lastState: {}                                                                                                                                                                      
    name: helm-charts-oci-proxy                                                                                                                                                        
    ready: false                                                                                                                                                                       
    restartCount: 0                                                                                                                                                                    
    started: false                                                                                                                                                                     
    state:                                                                                                                                                                             
      waiting:                                                                                                                                                                         
        message: 'failed to generate container "6cd9d03f49847aa4fcef5d232e64b0ef8e5632a210a0f52ef5f712ea99fd8726"                                                                      
          spec: failed to generate spec: no command specified'                                                                                                                         
        reason: CreateContainerError                                                                                                                                                   
```

It seems that 8gears.container-registry.com/library/helm-charts-oci-proxy:1.2.2 contains an helm oci release 

Properly pulled OCI chart
```
helm pull oci://8gears.container-registry.com/library/helm-charts-oci-proxy:1.2.2
Pulled: 8gears.container-registry.com/library/helm-charts-oci-proxy:1.2.2
Digest: sha256:7cdc3ccb31adac1bbe602bd95c6eb846d85d856846d44a3a9a9d6b268f2305fb
```

The readme advices the OCI image to run the proxy:
https://github.com/container-registry/helm-charts-oci-proxy/blob/f9bc9d4afbe6bee4888cf99595c5b1bf805a079f/README.md?plain=1#L78-L83

failed to docker pull 1.2.2 and 1.2.3 but success on `latest tag`, see https://github.com/actions/actions-runner-controller/discussions/2756#discussioncomment-8058830
```
# docker pull 8gears.container-registry.com/library/helm-charts-oci-proxy:1.2.2
1.2.2: Pulling from library/helm-charts-oci-proxy
unsupported media type application/vnd.cncf.helm.config.v1+json


# docker pull 8gears.container-registry.com/library/helm-charts-oci-proxy:latest
latest: Pulling from library/helm-charts-oci-proxy
a245e95e610b: Pull complete 
a573bd4f854c: Pull complete 
Digest: sha256:5b20d3cb79a5671dafe0b7e4ec57b4c7ef371a4722e4ae7b4e0bec0d6d6a8c85
Status: Downloaded newer image for 8gears.container-registry.com/library/helm-charts-oci-proxy:latest
8gears.container-registry.com/library/helm-charts-oci-proxy:latest


# docker pull 8gears.container-registry.com/library/helm-charts-oci-proxy:1.2.3
1.2.3: Pulling from library/helm-charts-oci-proxy
unsupported media type application/vnd.cncf.helm.config.v1+json
```

The github workflow seems to publish the proxy image through, could you please share the value of the `REGISTRY_ADDR` env var ?
https://github.com/container-registry/helm-charts-oci-proxy/blob/f9bc9d4afbe6bee4888cf99595c5b1bf805a079f/.github/workflows/build-release.yaml#L89-L96
